name: ohzas
description: A new Flutter application.
version: 1.000.006+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  shared_preferences: 0.5.6+1
  connectivity: 0.4.8+2
  fluttertoast: 3.1.3
  flutter_screenutil: ^0.4.2
  http: ^0.12.0+3
  get_version: 0.2.2
  package_info: 0.4.0+16
  datetime_picker_formfield: 1.0.0
  intl: 0.16.1
  toast: ^0.1.5
  url_launcher: ^5.4.10
  share: 0.6.4+3
  firebase_messaging: 6.0.16
  firebase_analytics: ^5.0.16
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/xlayer_logo_v2.png
    - assets/image_01.png
    - assets/image_02.png
    - assets/logo.png
    - assets/logo.jpg
    - assets/pf_back_1600x900.jpg
    - assets/loading_wt.gif
    - assets/discount.png
    - assets/discount_new.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins-Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf

    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
